### ISSUE TITLE
Missing fields for some parts

### ISSUE THREAD

**Issue by michaelbarrlycke** [alexist-ong/ninja-forms-polylang#1]
Hello!

just tested your plugin on a stage site. Amazing that you created this. I thank you so much!
A thing I saw here is that radio and some check boxes aren't getting into polylang.

How can I assist you into fetching these as well?

**Comment by carcam** [comment]
Hi @michaelbarrlycke ,
I had the same issue as you are facing and I fixed it adding this code in file class_NF_PLL.php at line 68, just after the foreach:

`
if ($field_key == "options") {
    pll_register_string('Field: ' . $field_key, $field_settings[$field_key][0]['label'], $group);
}
`

and code below to line 108 just after the foreach:

`
if ($field_key == "options") {
    $field_settings[$field_key][0]['label'] = pll__($field_settings[$field_key][0]['label']);
}
`

That should register the options labels and also translate them.

**Comment by carcam** [comment]
Here you have a PR with my proposal: 
https://github.com/alexist-ong/ninja-forms-polylang/pull/2

**Comment by michaelbarrlycke** [comment]
Hi @carcam 
I've added your strings but the fields are not showing up in Polylang for some reason. Did you get this to work?

**Comment by alexist-ong** [comment]
Hi @michaelbarrlycke,
Sorry for the late update. Yes, you are right. I missed those parts, thanks for reminding me. I have added them in version 3.1.0, you can check it out now.

Hi @carcam,
Thanks for your proposal. But similar to @michaelbarrlycke, I couldn't get it work too with the changes you made.

**Comment by michaelbarrlycke** [comment]
@alexist-ong is there something I need to do when uploading the 2 new files via ftp? Reload it or such? I uploaded it. Went to polylang string and there is no new fields there.

**Comment by michaelbarrlycke** [comment]
@alexist-ong i deleted the files on ftp. went to string section in polylang. The fields went away. I uploaded your updated files. went back to string section; now the check fileds are there :) Some hickup perhaps - working now :D

**Comment by alexist-ong** [comment]
@michaelbarrlycke , glad that you got it working. I'll be closing this ticket soon. Thank you so much for everything.

**Comment by carcam** [comment]
Thank you very much @alexist-ong !! Indeed my code was partially working for me, so I finally installed 3.1.0 ;)

Thank you very much for this nice piece of code!!

**Comment by alexist-ong** [comment]
You are welcome @carcam and have a nice day :)
